version: '3'
services:
  # ------ Load balancing and Reverse proxy ------
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - cherrypyboiler
  # ------ Web application interface ------
  web:
    build: ./web
    volumes:
      - ./web/build:/usr/share/nginx/html
  # ------ Sensor data DB -------
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
  # ------ Chertypy test ---------
  cherrypyboiler:
    build: ./cherrypyboiler
    volumes:
      - ./cherrypyboiler:/usr/src/app
    environment:
      - TELEMETRIC=temperature
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
    ports:
      - "5001:5001"
    depends_on:
      - db
    restart: on-failure
  # ------ Sessions service ------
  #rustboiler:
  #  build: ./rustboiler
  #  restart: on-failure
