version: '3'
services:
  # ------ Load balancing and Reverse proxy ------
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web-realtime
      - session
  web-realtime:
    image: grafana/grafana:latest
    expose: 
    - "3000"
    volumes:
    - /web-realtime/data:/var/lib/grafana
  # ------ Sessions service ------
  session:
    build: ./session
    volumes:
      - ./session/src:/usr/src/app
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
    depends_on:
      - db-session
    restart: on-failure
  db-session:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
