version: '3'
services:
  # ------ Load balancing and Reverse proxy ------
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rustboiler
  # ------ Sessions service ------
  rustboiler:
    build: ./rustboiler
    #volumes:
    #  - ./rustboiler/src:/usr/src/app
    restart: on-failure
