[package]
name = "rpmsensor"
version = "0.1.0"
authors = ["João Santos <joao.mp.santos@ua.pt>"]
edition = "2018"
publish = false


[dependencies]
rocket = "0.4.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.rocket_contrib]
default-features = false
features = ["json"]
